In [22]:
import numpy as np

In [23]:
# (3,4) boyutunda bir dizi oluşturunuz. Oluşturduğunuz bu dizinin boyutunu (6,2) olacak şekilde değiştiriniz
dizi=np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])
print(dizi)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [24]:
newarray=dizi.reshape(6,2)
print(newarray)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]]
