In [27]:
import numpy as np

In [25]:
#İki tane (3,3) boyutunda rastgele sayılardan bir dizi oluşturunuz. Oluşturulan bu diziyi
#hem yatay hem de dikey olacak şekilde istif (stack) ediniz

In [31]:
dizi1=([[10,11,12],[14,15,16],[18,19,20]])
dizi2=([[22,23,24],[25,26,27],[29,30,31]])

In [32]:
print(np.vstack((dizi1,dizi2)))

[[10 11 12]
 [14 15 16]
 [18 19 20]
 [22 23 24]
 [25 26 27]
 [29 30 31]]


In [33]:
print(np.column_stack((dizi1,dizi2)))

[[10 11 12 22 23 24]
 [14 15 16 25 26 27]
 [18 19 20 29 30 31]]
